2024-06-28 21:48:08.929898 - ERROR : send/read tcp data error: Traceback (most recent call last):
  File "d:\Project\Coding\PyAibote\PyAibote\Tool\SendTcpData.py", line 25, in SendData
    response = self.StarLoadWait(data)
  File "d:\Project\Coding\PyAibote\PyAibote\AndroidBotModel\AndroidLoadWait.py", line 40, in StarLoadWait
    response = self._Send(data)
  File "d:\Project\Coding\PyAibote\PyAibote\AndroidBotModel\AndroidLoadWait.py", line 24, in _Send
    response = self.request.recv(87654)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

