2024-04-30 09:24:48.111890 - ERROR : send/read tcp data error: Traceback (most recent call last):
  File "d:\Project\Coding\PyAibote\PyAibote\Tool\SendTcpData.py", line 25, in SendData
    response = self.StarLoadWait(data)
  File "d:\Project\Coding\PyAibote\PyAibote\WindowsBotModel\WinLoadWait.py", line 40, in StarLoadWait
    response = self._Send(data)
  File "d:\Project\Coding\PyAibote\PyAibote\WindowsBotModel\WinLoadWait.py", line 21, in _Send
    self.request.sendall(data)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

2024-04-30 09:25:39.566491 - ERROR : send/read tcp data error: Traceback (most recent call last):
  File "d:\Project\Coding\PyAibote\PyAibote\Tool\SendTcpData.py", line 25, in SendData
    response = self.StarLoadWait(data)
  File "d:\Project\Coding\PyAibote\PyAibote\WindowsBotModel\WinLoadWait.py", line 40, in StarLoadWait
    response = self._Send(data)
  File "d:\Project\Coding\PyAibote\PyAibote\WindowsBotModel\WinLoadWait.py", line 21, in _Send
    self.request.sendall(data)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

2024-04-30 09:26:52.206136 - ERROR : send/read tcp data error: Traceback (most recent call last):
  File "d:\Project\Coding\PyAibote\PyAibote\Tool\SendTcpData.py", line 25, in SendData
    response = self.StarLoadWait(data)
  File "d:\Project\Coding\PyAibote\PyAibote\WindowsBotModel\WinLoadWait.py", line 40, in StarLoadWait
    response = self._Send(data)
  File "d:\Project\Coding\PyAibote\PyAibote\WindowsBotModel\WinLoadWait.py", line 21, in _Send
    self.request.sendall(data)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

2024-04-30 09:27:34.838382 - ERROR : send/read tcp data error: Traceback (most recent call last):
  File "d:\Project\Coding\PyAibote\PyAibote\Tool\SendTcpData.py", line 25, in SendData
    response = self.StarLoadWait(data)
  File "d:\Project\Coding\PyAibote\PyAibote\WindowsBotModel\WinLoadWait.py", line 40, in StarLoadWait
    response = self._Send(data)
  File "d:\Project\Coding\PyAibote\PyAibote\WindowsBotModel\WinLoadWait.py", line 21, in _Send
    self.request.sendall(data)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

2024-04-30 09:29:28.217775 - ERROR : send/read tcp data error: Traceback (most recent call last):
  File "d:\Project\Coding\PyAibote\PyAibote\Tool\SendTcpData.py", line 25, in SendData
    response = self.StarLoadWait(data)
  File "d:\Project\Coding\PyAibote\PyAibote\WindowsBotModel\WinLoadWait.py", line 40, in StarLoadWait
    response = self._Send(data)
  File "d:\Project\Coding\PyAibote\PyAibote\WindowsBotModel\WinLoadWait.py", line 21, in _Send
    self.request.sendall(data)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

2024-04-30 09:30:10.932045 - ERROR : send/read tcp data error: Traceback (most recent call last):
  File "d:\Project\Coding\PyAibote\PyAibote\Tool\SendTcpData.py", line 25, in SendData
    response = self.StarLoadWait(data)
  File "d:\Project\Coding\PyAibote\PyAibote\WindowsBotModel\WinLoadWait.py", line 40, in StarLoadWait
    response = self._Send(data)
  File "d:\Project\Coding\PyAibote\PyAibote\WindowsBotModel\WinLoadWait.py", line 21, in _Send
    self.request.sendall(data)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

2024-04-30 09:49:21.279016 - ERROR : send/read tcp data error: Traceback (most recent call last):
  File "d:\Project\Coding\PyAibote\PyAibote\Tool\SendTcpData.py", line 25, in SendData
    response = self.StarLoadWait(data)
  File "d:\Project\Coding\PyAibote\PyAibote\WindowsBotModel\WinLoadWait.py", line 40, in StarLoadWait
    response = self._Send(data)
  File "d:\Project\Coding\PyAibote\PyAibote\WindowsBotModel\WinLoadWait.py", line 22, in _Send
    response = self.request.recv(87654)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

2024-04-30 09:49:55.723442 - ERROR : send/read tcp data error: Traceback (most recent call last):
  File "d:\Project\Coding\PyAibote\PyAibote\Tool\SendTcpData.py", line 25, in SendData
    response = self.StarLoadWait(data)
  File "d:\Project\Coding\PyAibote\PyAibote\WindowsBotModel\WinLoadWait.py", line 40, in StarLoadWait
    response = self._Send(data)
  File "d:\Project\Coding\PyAibote\PyAibote\WindowsBotModel\WinLoadWait.py", line 22, in _Send
    response = self.request.recv(87654)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

2024-04-30 09:50:35.837838 - ERROR : send/read tcp data error: Traceback (most recent call last):
  File "d:\Project\Coding\PyAibote\PyAibote\Tool\SendTcpData.py", line 25, in SendData
    response = self.StarLoadWait(data)
  File "d:\Project\Coding\PyAibote\PyAibote\WindowsBotModel\WinLoadWait.py", line 40, in StarLoadWait
    response = self._Send(data)
  File "d:\Project\Coding\PyAibote\PyAibote\WindowsBotModel\WinLoadWait.py", line 22, in _Send
    response = self.request.recv(87654)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

2024-04-30 09:52:18.369362 - ERROR : send/read tcp data error: Traceback (most recent call last):
  File "d:\Project\Coding\PyAibote\PyAibote\Tool\SendTcpData.py", line 25, in SendData
    response = self.StarLoadWait(data)
  File "d:\Project\Coding\PyAibote\PyAibote\WindowsBotModel\WinLoadWait.py", line 40, in StarLoadWait
    response = self._Send(data)
  File "d:\Project\Coding\PyAibote\PyAibote\WindowsBotModel\WinLoadWait.py", line 22, in _Send
    response = self.request.recv(87654)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

2024-04-30 11:04:31.835188 - ERROR : send/read tcp data error: Traceback (most recent call last):
  File "d:\Project\Coding\PyAibote\PyAibote\Tool\SendTcpData.py", line 25, in SendData
    response = self.StarLoadWait(data)
  File "d:\Project\Coding\PyAibote\PyAibote\WindowsBotModel\WinLoadWait.py", line 40, in StarLoadWait
    response = self._Send(data)
  File "d:\Project\Coding\PyAibote\PyAibote\WindowsBotModel\WinLoadWait.py", line 22, in _Send
    response = self.request.recv(87654)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

2024-04-30 11:06:07.274102 - ERROR : send/read tcp data error: Traceback (most recent call last):
  File "d:\Project\Coding\PyAibote\PyAibote\Tool\SendTcpData.py", line 25, in SendData
    response = self.StarLoadWait(data)
  File "d:\Project\Coding\PyAibote\PyAibote\WindowsBotModel\WinLoadWait.py", line 40, in StarLoadWait
    response = self._Send(data)
  File "d:\Project\Coding\PyAibote\PyAibote\WindowsBotModel\WinLoadWait.py", line 22, in _Send
    response = self.request.recv(87654)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

2024-04-30 11:09:43.589501 - ERROR : send/read tcp data error: Traceback (most recent call last):
  File "d:\Project\Coding\PyAibote\PyAibote\Tool\SendTcpData.py", line 25, in SendData
    response = self.StarLoadWait(data)
  File "d:\Project\Coding\PyAibote\PyAibote\WindowsBotModel\WinLoadWait.py", line 40, in StarLoadWait
    response = self._Send(data)
  File "d:\Project\Coding\PyAibote\PyAibote\WindowsBotModel\WinLoadWait.py", line 22, in _Send
    response = self.request.recv(87654)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

2024-04-30 11:15:44.376329 - ERROR : send/read tcp data error: Traceback (most recent call last):
  File "d:\Project\Coding\PyAibote\PyAibote\Tool\SendTcpData.py", line 25, in SendData
    response = self.StarLoadWait(data)
  File "d:\Project\Coding\PyAibote\PyAibote\WindowsBotModel\WinLoadWait.py", line 40, in StarLoadWait
    response = self._Send(data)
  File "d:\Project\Coding\PyAibote\PyAibote\WindowsBotModel\WinLoadWait.py", line 22, in _Send
    response = self.request.recv(87654)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

2024-04-30 11:36:21.515370 - ERROR : send/read tcp data error: Traceback (most recent call last):
  File "d:\Project\Coding\PyAibote\PyAibote\Tool\SendTcpData.py", line 25, in SendData
    response = self.StarLoadWait(data)
  File "d:\Project\Coding\PyAibote\PyAibote\WindowsBotModel\WinLoadWait.py", line 40, in StarLoadWait
    response = self._Send(data)
  File "d:\Project\Coding\PyAibote\PyAibote\WindowsBotModel\WinLoadWait.py", line 22, in _Send
    response = self.request.recv(87654)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

