2024-01-11 00:13:12.351564 - ERROR : send/read tcp data error: Traceback (most recent call last):
  File "d:\Project\Coding\PYAIBOTE\PyAibote\WebBotModel\SendTcpData.py", line 27, in SendData
    response = self.StarLoadWait(data)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Project\Coding\PYAIBOTE\PyAibote\WebBotModel\LoadWait.py", line 39, in StarLoadWait
    raise "Unable to find the specified element"
TypeError: exceptions must derive from BaseException

2024-01-11 00:26:40.734478 - ERROR : send/read tcp data error: Traceback (most recent call last):
  File "d:\Project\Coding\PYAIBOTE\PyAibote\WebBotModel\SendTcpData.py", line 27, in SendData
    response = self.StarLoadWait(data)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Project\Coding\PYAIBOTE\PyAibote\WebBotModel\LoadWait.py", line 39, in StarLoadWait
    raise "Unable to find the specified element"
TypeError: exceptions must derive from BaseException

2024-01-11 00:28:13.958319 - ERROR : send/read tcp data error: Traceback (most recent call last):
  File "d:\Project\Coding\PYAIBOTE\PyAibote\WebBotModel\SendTcpData.py", line 27, in SendData
    response = self.StarLoadWait(data)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Project\Coding\PYAIBOTE\PyAibote\WebBotModel\LoadWait.py", line 39, in StarLoadWait
    raise "Unable to find the specified element"
TypeError: exceptions must derive from BaseException

2024-01-11 00:29:11.853278 - ERROR : send/read tcp data error: Traceback (most recent call last):
  File "d:\Project\Coding\PYAIBOTE\PyAibote\WebBotModel\SendTcpData.py", line 27, in SendData
    response = self.StarLoadWait(data)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Project\Coding\PYAIBOTE\PyAibote\WebBotModel\LoadWait.py", line 39, in StarLoadWait
    raise "Unable to find the specified element"
TypeError: exceptions must derive from BaseException

2024-01-11 00:30:12.601673 - ERROR : send/read tcp data error: Traceback (most recent call last):
  File "d:\Project\Coding\PYAIBOTE\PyAibote\WebBotModel\SendTcpData.py", line 27, in SendData
    response = self.StarLoadWait(data)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Project\Coding\PYAIBOTE\PyAibote\WebBotModel\LoadWait.py", line 39, in StarLoadWait
    raise "Unable to find the specified element"
TypeError: exceptions must derive from BaseException

2024-01-11 18:10:10.157545 - ERROR : send/read tcp data error: Traceback (most recent call last):
  File "d:\Project\Coding\PYAIBOTE\PyAibote\WebBotModel\SendTcpData.py", line 27, in SendData
    response = self.StarLoadWait(data)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Project\Coding\PYAIBOTE\PyAibote\WebBotModel\LoadWait.py", line 29, in StarLoadWait
    response = self._Send(data)
               ^^^^^^^^^^^^^^^^
  File "d:\Project\Coding\PYAIBOTE\PyAibote\WebBotModel\LoadWait.py", line 21, in _Send
    response = self.request.recv(65535)
               ^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

2024-01-11 18:11:51.398900 - ERROR : send/read tcp data error: Traceback (most recent call last):
  File "d:\Project\Coding\PYAIBOTE\PyAibote\WebBotModel\SendTcpData.py", line 27, in SendData
    response = self.StarLoadWait(data)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Project\Coding\PYAIBOTE\PyAibote\WebBotModel\LoadWait.py", line 29, in StarLoadWait
    response = self._Send(data)
               ^^^^^^^^^^^^^^^^
  File "d:\Project\Coding\PYAIBOTE\PyAibote\WebBotModel\LoadWait.py", line 21, in _Send
    response = self.request.recv(65535)
               ^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

