2024-01-16 05:50:25.975711 - ERROR : send/read tcp data error: Traceback (most recent call last):
  File "d:\Project\Coding\PYAIBOTE\PyAibote\Tool\SendTcpData.py", line 27, in SendData
    response = self.StarLoadWait(data)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Project\Coding\PYAIBOTE\PyAibote\WindowsBotModel\WinLoadWait.py", line 33, in StarLoadWait
    response = self._Send(data)
               ^^^^^^^^^^^^^^^^
  File "d:\Project\Coding\PYAIBOTE\PyAibote\WindowsBotModel\WinLoadWait.py", line 22, in _Send
    response = self.request.recv(65535)
               ^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

2024-01-16 05:57:20.363173 - ERROR : send/read tcp data error: Traceback (most recent call last):
  File "d:\Project\Coding\PYAIBOTE\PyAibote\Tool\SendTcpData.py", line 27, in SendData
    response = self.StarLoadWait(data)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Project\Coding\PYAIBOTE\PyAibote\WindowsBotModel\WinLoadWait.py", line 33, in StarLoadWait
    response = self._Send(data)
               ^^^^^^^^^^^^^^^^
  File "d:\Project\Coding\PYAIBOTE\PyAibote\WindowsBotModel\WinLoadWait.py", line 22, in _Send
    response = self.request.recv(65535)
               ^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

2024-01-16 06:16:27.793414 - ERROR : send/read tcp data error: Traceback (most recent call last):
  File "d:\Project\Coding\PYAIBOTE\PyAibote\Tool\SendTcpData.py", line 27, in SendData
    response = self.StarLoadWait(data)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Project\Coding\PYAIBOTE\PyAibote\WindowsBotModel\WinLoadWait.py", line 33, in StarLoadWait
    response = self._Send(data)
               ^^^^^^^^^^^^^^^^
  File "d:\Project\Coding\PYAIBOTE\PyAibote\WindowsBotModel\WinLoadWait.py", line 22, in _Send
    response = self.request.recv(65535)
               ^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

