2024-07-11 08:58:13.397359 - ERROR : send/read tcp data error: Traceback (most recent call last):
  File "d:\Project\Coding\PyAibote\PyAibote\Tool\SendTcpData.py", line 25, in SendData
    response = self.StarLoadWait(data)
  File "d:\Project\Coding\PyAibote\PyAibote\WindowsBotModel\WinLoadWait.py", line 42, in StarLoadWait
    response = self._Send(data)
  File "d:\Project\Coding\PyAibote\PyAibote\WindowsBotModel\WinLoadWait.py", line 22, in _Send
    response = self.request.recv(87654)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

2024-07-11 08:59:31.707154 - ERROR : send/read tcp data error: Traceback (most recent call last):
  File "d:\Project\Coding\PyAibote\PyAibote\Tool\SendTcpData.py", line 25, in SendData
    response = self.StarLoadWait(data)
  File "d:\Project\Coding\PyAibote\PyAibote\WindowsBotModel\WinLoadWait.py", line 42, in StarLoadWait
    response = self._Send(data)
  File "d:\Project\Coding\PyAibote\PyAibote\WindowsBotModel\WinLoadWait.py", line 22, in _Send
    response = self.request.recv(87654)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

2024-07-11 09:01:00.234951 - ERROR : send/read tcp data error: Traceback (most recent call last):
  File "d:\Project\Coding\PyAibote\PyAibote\Tool\SendTcpData.py", line 25, in SendData
    response = self.StarLoadWait(data)
  File "d:\Project\Coding\PyAibote\PyAibote\WindowsBotModel\WinLoadWait.py", line 42, in StarLoadWait
    response = self._Send(data)
  File "d:\Project\Coding\PyAibote\PyAibote\WindowsBotModel\WinLoadWait.py", line 22, in _Send
    response = self.request.recv(87654)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

2024-07-11 09:10:16.357558 - ERROR : send/read tcp data error: Traceback (most recent call last):
  File "d:\Project\Coding\PyAibote\PyAibote\Tool\SendTcpData.py", line 25, in SendData
    response = self.StarLoadWait(data)
  File "d:\Project\Coding\PyAibote\PyAibote\WindowsBotModel\WinLoadWait.py", line 42, in StarLoadWait
    response = self._Send(data)
  File "d:\Project\Coding\PyAibote\PyAibote\WindowsBotModel\WinLoadWait.py", line 22, in _Send
    response = self.request.recv(87654)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

2024-07-11 09:25:02.823813 - ERROR : send/read tcp data error: Traceback (most recent call last):
  File "d:\Project\Coding\PyAibote\PyAibote\Tool\SendTcpData.py", line 25, in SendData
    response = self.StarLoadWait(data)
  File "d:\Project\Coding\PyAibote\PyAibote\WindowsBotModel\WinLoadWait.py", line 42, in StarLoadWait
    response = self._Send(data)
  File "d:\Project\Coding\PyAibote\PyAibote\WindowsBotModel\WinLoadWait.py", line 22, in _Send
    response = self.request.recv(87654)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

2024-07-11 11:30:10.866316 - ERROR : send/read tcp data error: Traceback (most recent call last):
  File "d:\Project\Coding\PyAibote\PyAibote\Tool\SendTcpData.py", line 25, in SendData
    response = self.StarLoadWait(data)
  File "d:\Project\Coding\PyAibote\PyAibote\WindowsBotModel\WinLoadWait.py", line 42, in StarLoadWait
    response = self._Send(data)
  File "d:\Project\Coding\PyAibote\PyAibote\WindowsBotModel\WinLoadWait.py", line 22, in _Send
    response = self.request.recv(87654)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

2024-07-11 20:22:58.843441 - ERROR : send/read tcp data error: Traceback (most recent call last):
  File "d:\Project\Coding\PyAibote\PyAibote\Tool\SendTcpData.py", line 25, in SendData
    response = self.StarLoadWait(data)
  File "d:\Project\Coding\PyAibote\PyAibote\AndroidBotModel\AndroidLoadWait.py", line 40, in StarLoadWait
    response = self._Send(data)
  File "d:\Project\Coding\PyAibote\PyAibote\AndroidBotModel\AndroidLoadWait.py", line 27, in _Send
    raise ConnectionAbortedError(f"{self.client_address[0]}:{self.client_address[1]} Client disconnects")
ConnectionAbortedError: 192.168.31.23:44342 Client disconnects

